version: '3.3'

services: 
    app:
        build: .
        container_name: app
        volumes: 
            - .:/app
        working_dir: /app
        ports: 
            - 8080:8080
        command: ['yarn', 'dev']

    e2e:
      build: ./cypress
      container_name: e2e
      restart: unless-stopped
      depends_on:
        - app
      environment:
        - CYPRESS_baseUrl=http://localhost:8080
      working_dir: /e2e
      volumes:
        - ./:/e2e
